### ISSUE TITLE
call to is.float()

### ISSUE THREAD

**Issue by arodri7** [wrathematics/hdfmat#1]
https://github.com/wrathematics/hdfmat/blob/63e9c4bae9934ed9863b73b7fdd9bf71edfd1efe/R/hdfmat.r#L96

Should the call to is.float() be float::is.float() ?

**Comment by wrathematics** [comment]
I import all of the float package, so it's not strictly necessary. But I try to namespace for readability. So it should work as is, but my preference is for `float::is.float()`.

**Comment by wrathematics** [comment]
Addressed here https://github.com/wrathematics/hdfmat/commit/3bd424279ba3ec0751ff362226f97cdfc5c295e6
